platform :ios, '7.0'

pod 'SDWebImage'
pod 'AFNetworking', '~> 3.0.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SSCheckBoxView', '~> 0.0.1'
pod 'QuickDialog', '~> 1.1.0'
pod 'MJRefresh', '~> 3.0.8'
pod 'EaseMobSDK', :git => 'https://github.com/easemob/sdk-ios-cocoapods.git'
